/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppUploadRouteImport } from './routes/app/upload'
import { Route as AppTermsRouteImport } from './routes/app/terms'
import { Route as AppRegisterbakRouteImport } from './routes/app/registerbak'
import { Route as AppRegisterRouteImport } from './routes/app/register'
import { Route as AppPricingRouteImport } from './routes/app/pricing'
import { Route as AppLoginRouteImport } from './routes/app/login'
import { Route as AppGuestRouteImport } from './routes/app/guest'
import { Route as AppFilesRouteImport } from './routes/app/files'
import { Route as AppContactRouteImport } from './routes/app/contact'
import { Route as AppAboutRouteImport } from './routes/app/about'

const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUploadRoute = AppUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => AppRoute,
} as any)
const AppTermsRoute = AppTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => AppRoute,
} as any)
const AppRegisterbakRoute = AppRegisterbakRouteImport.update({
  id: '/registerbak',
  path: '/registerbak',
  getParentRoute: () => AppRoute,
} as any)
const AppRegisterRoute = AppRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AppRoute,
} as any)
const AppPricingRoute = AppPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => AppRoute,
} as any)
const AppLoginRoute = AppLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AppRoute,
} as any)
const AppGuestRoute = AppGuestRouteImport.update({
  id: '/guest',
  path: '/guest',
  getParentRoute: () => AppRoute,
} as any)
const AppFilesRoute = AppFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => AppRoute,
} as any)
const AppContactRoute = AppContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => AppRoute,
} as any)
const AppAboutRoute = AppAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/about': typeof AppAboutRoute
  '/app/contact': typeof AppContactRoute
  '/app/files': typeof AppFilesRoute
  '/app/guest': typeof AppGuestRoute
  '/app/login': typeof AppLoginRoute
  '/app/pricing': typeof AppPricingRoute
  '/app/register': typeof AppRegisterRoute
  '/app/registerbak': typeof AppRegisterbakRoute
  '/app/terms': typeof AppTermsRoute
  '/app/upload': typeof AppUploadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/about': typeof AppAboutRoute
  '/app/contact': typeof AppContactRoute
  '/app/files': typeof AppFilesRoute
  '/app/guest': typeof AppGuestRoute
  '/app/login': typeof AppLoginRoute
  '/app/pricing': typeof AppPricingRoute
  '/app/register': typeof AppRegisterRoute
  '/app/registerbak': typeof AppRegisterbakRoute
  '/app/terms': typeof AppTermsRoute
  '/app/upload': typeof AppUploadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/about': typeof AppAboutRoute
  '/app/contact': typeof AppContactRoute
  '/app/files': typeof AppFilesRoute
  '/app/guest': typeof AppGuestRoute
  '/app/login': typeof AppLoginRoute
  '/app/pricing': typeof AppPricingRoute
  '/app/register': typeof AppRegisterRoute
  '/app/registerbak': typeof AppRegisterbakRoute
  '/app/terms': typeof AppTermsRoute
  '/app/upload': typeof AppUploadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/about'
    | '/app/contact'
    | '/app/files'
    | '/app/guest'
    | '/app/login'
    | '/app/pricing'
    | '/app/register'
    | '/app/registerbak'
    | '/app/terms'
    | '/app/upload'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/app/about'
    | '/app/contact'
    | '/app/files'
    | '/app/guest'
    | '/app/login'
    | '/app/pricing'
    | '/app/register'
    | '/app/registerbak'
    | '/app/terms'
    | '/app/upload'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/about'
    | '/app/contact'
    | '/app/files'
    | '/app/guest'
    | '/app/login'
    | '/app/pricing'
    | '/app/register'
    | '/app/registerbak'
    | '/app/terms'
    | '/app/upload'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/upload': {
      id: '/app/upload'
      path: '/upload'
      fullPath: '/app/upload'
      preLoaderRoute: typeof AppUploadRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/terms': {
      id: '/app/terms'
      path: '/terms'
      fullPath: '/app/terms'
      preLoaderRoute: typeof AppTermsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/registerbak': {
      id: '/app/registerbak'
      path: '/registerbak'
      fullPath: '/app/registerbak'
      preLoaderRoute: typeof AppRegisterbakRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/register': {
      id: '/app/register'
      path: '/register'
      fullPath: '/app/register'
      preLoaderRoute: typeof AppRegisterRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/pricing': {
      id: '/app/pricing'
      path: '/pricing'
      fullPath: '/app/pricing'
      preLoaderRoute: typeof AppPricingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/login': {
      id: '/app/login'
      path: '/login'
      fullPath: '/app/login'
      preLoaderRoute: typeof AppLoginRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/guest': {
      id: '/app/guest'
      path: '/guest'
      fullPath: '/app/guest'
      preLoaderRoute: typeof AppGuestRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/files': {
      id: '/app/files'
      path: '/files'
      fullPath: '/app/files'
      preLoaderRoute: typeof AppFilesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/contact': {
      id: '/app/contact'
      path: '/contact'
      fullPath: '/app/contact'
      preLoaderRoute: typeof AppContactRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/about': {
      id: '/app/about'
      path: '/about'
      fullPath: '/app/about'
      preLoaderRoute: typeof AppAboutRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAboutRoute: typeof AppAboutRoute
  AppContactRoute: typeof AppContactRoute
  AppFilesRoute: typeof AppFilesRoute
  AppGuestRoute: typeof AppGuestRoute
  AppLoginRoute: typeof AppLoginRoute
  AppPricingRoute: typeof AppPricingRoute
  AppRegisterRoute: typeof AppRegisterRoute
  AppRegisterbakRoute: typeof AppRegisterbakRoute
  AppTermsRoute: typeof AppTermsRoute
  AppUploadRoute: typeof AppUploadRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAboutRoute: AppAboutRoute,
  AppContactRoute: AppContactRoute,
  AppFilesRoute: AppFilesRoute,
  AppGuestRoute: AppGuestRoute,
  AppLoginRoute: AppLoginRoute,
  AppPricingRoute: AppPricingRoute,
  AppRegisterRoute: AppRegisterRoute,
  AppRegisterbakRoute: AppRegisterbakRoute,
  AppTermsRoute: AppTermsRoute,
  AppUploadRoute: AppUploadRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
